---

- name: Verify OS is Valid for awx_debian roles
  set_fact:
    awx_debian_os: True
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_version == '9' or 
      ansible_distribution_version == '10'

- name: Check for AWX Installation
  stat:
    path: "{{ awx_debian_home }}/venv/awx/bin/awx-manage"
  failed_when: not awx_debian_os
  register: awx_installed
  check_mode: no

- name: Check AWX Version if Installed
  command: "{{ awx_debian_home }}/venv/awx/bin/awx-manage --version"
  register: awx_version
  when: awx_installed.stat.exists
  failed_when: False
  check_mode: no

- name: Disable Build if AWX {{ awx_debian_ver }} is Installed 
  set_fact:
    awx_debian_build: False
  when:
    - awx_installed.stat.exists
    - awx_version.stdout is defined
    - awx_version.stdout == awx_debian_ver
  check_mode: no

- name: Stop AWX Services if Refreshing or Building
  systemd:
    state: stopped
    name: "{{ item }}"
    daemon_reload: yes
  failed_when: False
  with_items:
    - 'awx-django'
    - 'awx-daphne'
    - 'awx-dispatch'
    - 'awx-callback'
    - 'awx-workers'
  when: awx_debian_refresh or
        awx_debian_build

- name: Provision Dependent Services and Install Build Dependencies
  include_tasks: deps.yml

- name: Configure nginx
  include_tasks: nginx.yml

- name: Configure the postgres Database
  include_tasks: postgres.yml

- name: Build and Install AWX
  include_tasks: install.yml
  when: awx_debian_refresh or
        awx_debian_build

- name: Configure Standalone AWX 
  include_tasks: config.yml

- name: Start AWX Services
  include_tasks: services.yml
